# Generated by Django 5.1.4 on 2025-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestcaseRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcasename', models.CharField(max_length=200, unique=True)),
                ('testplatform', models.CharField(max_length=30)),
                ('testtype', models.CharField(max_length=50)),
            ],
        ),
    ]
