# Generated by Django 5.1.4 on 2024-12-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=200)),
                ('isClient', models.BooleanField(null=True)),
                ('hostname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=50)),
                ('WanIp', models.CharField(max_length=200)),
                ('rpcPort', models.IntegerField(default=7777)),
                ('rpcUrl', models.URLField(blank=True, null=True)),
                ('sshPort', models.IntegerField(default=22)),
                ('DevicePlatform', models.CharField(max_length=20)),
                ('lanIface', models.CharField(blank=True, max_length=20, null=True)),
                ('wanIface', models.CharField(blank=True, max_length=20, null=True)),
                ('wlanIface', models.CharField(blank=True, max_length=20, null=True)),
                ('extaprops', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestcaseHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseName', models.CharField(max_length=200)),
                ('testPlatform', models.CharField(max_length=30)),
                ('testArea', models.CharField(max_length=200)),
                ('testcaseDetails', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestSuiteHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testSuiteName', models.CharField(max_length=200)),
                ('testSuitePlatform', models.CharField(max_length=30)),
                ('testcaseList', models.JSONField()),
            ],
        ),
    ]
