# Generated by Django 5.1.4 on 2024-12-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceName', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('rpcIp', models.CharField(max_length=200)),
                ('rpcPort', models.IntegerField(default=7777)),
                ('rpcUrl', models.CharField(max_length=200)),
                ('sshPort', models.IntegerField(default=21)),
                ('DevicePlatform', models.CharField(max_length=20)),
                ('lanIface', models.CharField(max_length=20)),
                ('wanIface', models.CharField(max_length=20)),
                ('wlanIface', models.CharField(max_length=20)),
                ('extaprops', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TestcaseHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseName', models.CharField(max_length=200)),
                ('testPlatform', models.CharField(max_length=30)),
                ('testArea', models.CharField(max_length=200)),
                ('testcaseDetails', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
