# Generated by Django 5.1.4 on 2024-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehandler',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='devicehandler',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicehandler',
            name='sshPort',
            field=models.IntegerField(blank=True, default=22, null=True),
        ),
    ]
